import Head from "next/head";
import { useState, useEffect } from "react";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from "chart.js";
import { Line, Bar } from "react-chartjs-2";
import { useAppContext } from "../components/context";
import {
  FormLayout,
  SliderInput,
  RadioButton,
  InputBox,
  SelectBox,
} from "../components/FormComponents";

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  Title,
  Tooltip,
  Legend
);

export default function Home() {
  const {
    Population,
    options,
    data,
    genMembers,
    targetString,
    setTargetString,
    populationSize,
    setPopulationSize,
    generationCount,
    setGenerationCount,
    correctValsCount,
    mutationInputRate,
    setMutationInputRate,
    isLoading,
    setIsLoading,
  } = useAppContext();

  const [count, setCount] = useState(targetString.length);
  const [chartType, setChartType] = useState("line");

  const handleGenerate = (
    e,
    populationSize,
    target,
    mutationRate,
    generations
  ) => {
    e.preventDefault();
    if (populationSize > 200 || !target.length || generations > 300) return;
    setIsLoading(true);
    const population = new Population(populationSize, target, mutationRate);
    population.evolve(generations);
    setIsLoading(false);
  };

  const handleGenerateOnMount = (
    populationSize,
    target,
    mutationRate,
    generations
  ) => {
    const population = new Population(populationSize, target, mutationRate);
    population.evolve(generations);
    setIsLoading(false);
  };

  const handleTextChange = (e) => {
    const target = e.target.value;
    const countValue = e.target.value.length;
    setTargetString(target.replace(/\s+/g, "").toLowerCase());
    setCount(countValue);
  };

  useEffect(() => {
    handleGenerateOnMount(
      populationSize,
      targetString,
      mutationInputRate,
      generationCount
    );
  }, []);

  return (
    <div className="min-h-screen flex">
      <Head>
        <title>Genetic Algorithm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* SIDEBAR */}
      <div className="bg-slate-100 w-80 px-9 py-24 hidden lg:block">
        <div className="space-y-8 fixed">
          <h3 className="font-semibold">Parameters</h3>
          <form
            className="space-y-8"
            onSubmit={(e) =>
              handleGenerate(
                e,
                Math.abs(populationSize),
                targetString,
                mutationInputRate,
                Math.abs(generationCount)
              )
            }
          >
            <FormLayout inputLabel="Target String" condition="(letters only)">
              <div className="relative">
                <InputBox
                  type="text"
                  maxLength="4"
                  value={targetString}
                  onChange={handleTextChange}
                  isLoading={isLoading}
                />
                <p className="absolute top-4 right-2 font-light text-slate-400">
                  Limit: {count}/4
                </p>
              </div>
            </FormLayout>
            <FormLayout
              inputLabel="Population Size"
              condition="(min 20, max 200)"
            >
              <InputBox
                type="number"
                min="20"
                max="200"
                value={populationSize}
                onChange={(e) => setPopulationSize(e.target.value)}
                isLoading={isLoading}
              />
            </FormLayout>
            <FormLayout inputLabel="Mutation Rate">
              <SelectBox
                value={mutationInputRate}
                onChange={(e) => setMutationInputRate(e.target.value)}
                isLoading={isLoading}
              />
            </FormLayout>
            <FormLayout
              inputLabel="Generation Count"
              condition={`: ${generationCount}`}
            >
              <SliderInput
                value={generationCount}
                min={50}
                max={300}
                onChange={(e) => setGenerationCount(e.target.value)}
              />
            </FormLayout>
            <FormLayout inputLabel="Chart Type">
              <div
                onChange={(e) => setChartType(e.target.value)}
                className="space-x-8"
              >
                <RadioButton label="Line" value="line" chartType={chartType} />
                <RadioButton label="Bar" value="bar" chartType={chartType} />
              </div>
            </FormLayout>
            <button className="btn-primary" type="submit" disabled={isLoading}>
              Generate
            </button>
          </form>
        </div>
      </div>
      {/* MAIN-CONTAINER */}
      <div className="main-container">
        <div className="space-y-4">
          <h1 className="font-bold">Genetic Algorithm</h1>
          <p className="text-rose-500">Not yet fully compatible with mobile</p>
        </div>

        {/* table */}
        <div className="space-y-8">
          <h2 className="font-semibold">Evolutions Table</h2>
          <div className="overflow-auto h-96">
            <table className="w-full">
              <thead>
                <tr>
                  <th className="text-center">Generation</th>
                  <th className="px-4 md:px-16 text-center">Fitness</th>
                  <th className="text-left">Population</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {genMembers.map((members, i) => (
                  <tr key={i}>
                    <td className="text-center p-4">{i + 1}</td>
                    <td className="text-center">{correctValsCount[i]}</td>
                    <td className="">{members.join("_")}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
        {/* chart */}
        <div className="space-y-2">
          <h2 className="font-semibold">Fitness Value Chart</h2>
          <div>
            {chartType === "line" ? (
              <Line options={options} data={data} />
            ) : (
              <Bar options={options} data={data} />
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
