import Head from "next/head";
import { useState, useEffect } from "react";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from "chart.js";
import { Line, Bar } from "react-chartjs-2";
import { useAppContext } from "../components/context";
import {
  FormLayout,
  SliderInput,
  RadioButton,
  InputBox,
  SelectBox,
} from "../components/utils";
import { ChevronLeft, Settings, GithubLink } from "../components/icons";

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  Title,
  Tooltip,
  Legend
);

const TestPage = () => {
  const {
    Population,
    options,
    data,
    genMembers,
    targetString,
    setTargetString,
    populationSize,
    setPopulationSize,
    generationCount,
    setGenerationCount,
    correctValsCount,
    mutationRate,
    setMutationRate,
    chartDataY,
  } = useAppContext();

  const [count, setCount] = useState(targetString.length);
  const [chartType, setChartType] = useState("line");
  const [navIsOpen, setNavIsOpen] = useState(false);

  const [resultsGenerationCount, setResultsGenerationCount] =
    useState(generationCount);
  const [resultsTargetString, setResultsTargetString] = useState(targetString);

  const handleGenerate = (
    populationSize,
    targetString,
    mutationRate,
    generationCount
  ) => {
    const population = new Population(
      populationSize,
      targetString,
      mutationRate
    );
    // if (!targetString) return;
    population.evolve(generationCount);
    setResultsGenerationCount(generationCount);
    setResultsTargetString(targetString);
  };

  const handleGenerateOnMount = (
    populationSize,
    targetString,
    mutationRate,
    generationCount
  ) => {
    const population = new Population(
      populationSize,
      targetString,
      mutationRate
    );
    population.evolve(generationCount);
  };

  const handleSubmit = async (event) => {
    event.preventDefault();

    const data = {
      targetString,
      populationSize,
      generationCount,
    };

    const JSONdata = JSON.stringify(data);
    const endpoint = "/api/form";

    const options = {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSONdata,
    };

    const response = await fetch(endpoint, options);

    if (response.status !== 200) {
      return;
    }

    const result = await response.json();

    // console.log(`${response.status}`);
    // console.log(result.targetString);

    handleGenerate(
      result.populationSize,
      result.targetString,
      mutationRate,
      result.generationCount
    );
  };

  const handleTextChange = (e) => {
    const target = e.target.value.replace(/\s+/g, "");
    const countValue = target.length;
    setTargetString(target.toLowerCase());
    setCount(countValue);
  };

  useEffect(() => {
    handleGenerateOnMount(
      populationSize,
      targetString,
      mutationRate,
      generationCount
    );
  }, []);
  return (
    <div className="min-h-screen lg:flex relative lg:pl-80">
      <Head>
        <title>Word Matching - Genetic Algorithm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* overlay */}
      {navIsOpen && (
        <div
          onClick={() => setNavIsOpen(false)}
          className="fixed z-10 inset-0 w-full h-full bg-slate-900 opacity-30 lg:hidden"
        ></div>
      )}

      {/* mobile navbar */}
      <div className="fixed bg-white lg:bg-transparent p-2 w-full flex items-center justify-between lg:hidden">
        <button onClick={() => setNavIsOpen(true)} className="sidebar-open-btn">
          <Settings className="h-5 w-5 sm:h-7 sm:w-7" />
        </button>
        <GithubLink />
      </div>

      {/* SIDEBAR */}
      <nav
        className={`${
          navIsOpen === true ? "translate-x-0" : "-translate-x-full"
        } fixed inset-0 lg:transform-none duration-200 z-10 w-60 sm:w-80 bg-slate-100 flex items-center justify-center`}
      >
        <button
          onClick={() => setNavIsOpen(false)}
          className="sidebar-close-btn"
        >
          <ChevronLeft className="h-5 w-5 sm:h-7 sm:w-7" />
        </button>
        <GithubLink className="absolute bottom-2 right-2 hidden lg:block border-slate-100" />
        <div className="space-y-8 w-full px-4 sm:px-6">
          <h3 className="font-semibold">Settings</h3>
          <form className="space-y-8" onSubmit={handleSubmit}>
            <FormLayout inputLabel="Target String" condition="(letters only)">
              <div className="relative">
                <InputBox
                  type="text"
                  maxLength="4"
                  value={targetString}
                  onChange={handleTextChange}
                />
                <p className="absolute top-4 right-2 font-light text-slate-400">
                  Limit: {count}/4
                </p>
              </div>
            </FormLayout>
            <FormLayout
              inputLabel="Population Size"
              condition="(min 20, max 200)"
            >
              <InputBox
                type="number"
                min="20"
                max="200"
                value={populationSize}
                onChange={(e) => setPopulationSize(e.target.value)}
              />
            </FormLayout>
            <FormLayout inputLabel="Mutation Rate">
              <SelectBox
                value={mutationRate}
                onChange={(e) => setMutationRate(e.target.value)}
              />
            </FormLayout>
            <FormLayout
              inputLabel="Generation Count"
              condition={`: ${generationCount}`}
            >
              <SliderInput
                value={generationCount}
                min={50}
                max={300}
                onChange={(e) => setGenerationCount(e.target.value)}
              />
            </FormLayout>
            <FormLayout inputLabel="Chart Type">
              <div
                onChange={(e) => setChartType(e.target.value)}
                className="space-x-8"
              >
                <RadioButton label="Line" value="line" chartType={chartType} />
                <RadioButton label="Bar" value="bar" chartType={chartType} />
              </div>
            </FormLayout>
            <button className="btn-primary" type="submit">
              Generate
            </button>
          </form>
        </div>
      </nav>
      {/* MAIN-CONTAINER */}
      <div className="main-container overflow-auto">
        <div className="space-y-4">
          <h1 className="font-bold">Genetic Algorithm</h1>
        </div>
        {/* table */}
        <div className="space-y-6">
          <h2 className="font-semibold">Evolutions Table</h2>
          <div className="overflow-auto h-96">
            <table className="">
              <thead>
                <tr>
                  <th className="text-center">Generation</th>
                  <th className="px-4 md:px-16 text-center">Fitness</th>
                  <th className="text-left">Population</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {genMembers.map((members, i) => (
                  <tr key={i}>
                    <td className="text-center p-4">{i + 1}</td>
                    <td className="text-center">{correctValsCount[i]}</td>
                    <td className="">{members.join("_")}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
        {/* summary section */}
        <div className="space-y-6">
          <h2 className="font-semibold">Summary</h2>
          <div className="bg-slate-100 rounded font-mono leading-8 p-8 overflow-auto">
            Summary = &#123;
            <br />
            &nbsp;&nbsp;configuration = &#123;
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;totalGenerations: {resultsGenerationCount},
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;targetString: "{resultsTargetString}",
            <br />
            &nbsp;&nbsp;&#125;,
            <br />
            &nbsp;&nbsp;results = &#123;
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;matchingStringsCount:{" "}
            {chartDataY[chartDataY.length - 1]},
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;bestRecorded: &#123;
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;matchingStringsCount:{" "}
            {Math.max(...chartDataY)}
            ,
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;atGeneration:{" "}
            {chartDataY.indexOf(Math.max(...chartDataY)) + 1},<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&#125;,
            <br />
            &nbsp;&nbsp;&#125;,
            <br />
            &#125;
            {/* <ResultsLayout
              label={`${resultsGenerationCount} GENERATIONS:`}
              spanText={`${chartDataY[chartDataY.length - 1]} members`}
              pText="matched the target string"
            ></ResultsLayout>
            <ResultsLayout
              label="HIGHEST:"
              spanText={`${Math.max(...chartDataY)} members`}
              pText={`matched at generation ${
                chartDataY.indexOf(Math.max(...chartDataY)) + 1
              }`}
            ></ResultsLayout> */}
          </div>
        </div>
        {/* chart */}
        <div className="space-y-4">
          <h2 className="font-semibold">Fitness Value Chart</h2>
          <div>
            {chartType === "line" ? (
              <Line options={options} data={data} />
            ) : (
              <Bar options={options} data={data} />
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default TestPage;
